### ISSUE TITLE
Error on `npm run dev`

### ISSUE THREAD

**Issue by phase7** [agility/agilitycms-eleventy-starter-2020#3]
I wanted to try out Agility with Eleventy but ran into some problems. 
Following code snippet is error log on my console (running on Linux Mint Os based on Ubuntu 18.04)
```
> agility-cms-11ty-blog@1.0.0 dev
> run-s clean:files dev:* --print-label

[clean:files] 
[clean:files] > agility-cms-11ty-blog@1.0.0 clean:files
[clean:files] > del dist
[clean:files] 
[dev:cms    ] 
[dev:cms    ] > agility-cms-11ty-blog@1.0.0 dev:cms
[dev:cms    ] > NODE_ENV=development node agility/agility.sync.js sync
[dev:cms    ] 
[dev:cms    ] AgilityCMS => Starting Sync for en-us - preview mode. 
[dev:cms    ] AgilityCMS => Content Sync returned 28 item(s). 
[dev:cms    ] AgilityCMS => Page Sync returned 4 item(s). 
[dev:cms    ] AgilityCMS => Updating Sitemap channel website in en-us 
[dev:cms    ] AgilityCMS => URL Redirections Updated and Saved 
[dev:cms    ] AgilityCMS => Completed Sync for en-us - preview mode. 
[dev:css    ] 
[dev:css    ] > agility-cms-11ty-blog@1.0.0 dev:css
[dev:css    ] > NODE_ENV=production postcss src/css/index.css -o dist/styles.css
[dev:css    ] 
[dev:11ty   ] 
[dev:11ty   ] > agility-cms-11ty-blog@1.0.0 dev:11ty
[dev:11ty   ] > NODE_ENV=development eleventy
[dev:11ty   ] 
[dev:11ty   ] Agility CMS => Building site in preview mode.
[dev:11ty   ] > Cannot read property 'map' of undefined
[dev:11ty   ] 
[dev:11ty   ] `TypeError` was thrown:
[dev:11ty   ]     TypeError: Cannot read property 'map' of undefined
[dev:11ty   ]         at getAgilityContent (<project root folder>/src/_data/agilitypages.js:65:61)
[dev:11ty   ]         at async TemplateData.getDataValue (<project root folder>/node_modules/@11ty/eleventy/src/TemplateData.js:385:23)
[dev:11ty   ]         at async TemplateData.getAllGlobalData (<project root folder>/node_modules/@11ty/eleventy/src/TemplateData.js:228:18)
[dev:11ty   ]         at async TemplateData.getData (<project root folder>/node_modules/@11ty/eleventy/src/TemplateData.js:255:24)
ERROR: "dev:11ty" exited with 1.
```
## Steps to reproduce this error
1. Clone this repo
2. run `npm install`
3. add my own env variable to .env.example and rename it to .env
3. run `npm run dev`

## Expected behaviour 
1. Static site generated in preview mode

**Comment by joelvarty** [comment]
Hi there! Thanks for trying out Eleventy with Agility CMS! The step that you need to do is to create a free developer account with Agility CMS - instructions are on the readme of this repo.   

That will set up a project in the CMS with a pre-built content model for you to play around with.  It will also provide you with the API keys for the `.env` file 

Hope that makes sense.

**Comment by phase7** [comment]
I have an account, it's set up as a next blog template starter. 
As i've mentioned in step 3 of `Steps to reproduce this error`, I've gotten ENV variables from [https://manager.agilitycms.com/settings/apikeys](https://manager.agilitycms.com/settings/apikeys) and pasted them in `.env` file.
What else should I do?

**Comment by joelvarty** [comment]
@joshua-isaac Can you take a look and make sure our starter code is all good?  Might be useful if you could reach out to @phase7  and get the details of what is happening here.

**Comment by joshua-isaac** [comment]
@phase7 Hey Ratul! So the instance you signed up for is actually for our new nextjs template which has some new modules and stuff which i believe is causing you build to break.

If you have another email, check out this repo where you can sign up for the instance specific for the eleventy starter => https://github.com/agility/jamstack-blog-starters

If you need me to delete your instance so you can re-create one let me know :)

Our goal is to make a unified Blog Template that will work with any starter (Next.js, Gatsby, Nuxt, Eleventy etc), which we are currently working on.

Feel free to message me if you need any help, or join our community [slack channel](https://agilitycms-community.slack.com/join/shared_invite/zt-99qlv1hw-tpPOJ99V21Y2omtA_uTcJw) :)

**Comment by phase7** [comment]
Thanks for your replies. I would like to try a eleventy site. How do I go about delete and re-create my agility instance?

**Comment by joshua-isaac** [comment]
@phase7 join our community slack channel and ill shoot you a message and get you sorted out :)

**Comment by phase7** [comment]
Okay.
